name: spark_save
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  provider: ^6.1.2
  firebase_ui_auth: ^1.16.0
  go_router: ^14.6.2
  page_transition: ^2.1.0
  buttons_tabbar: ^1.3.14
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  accordion: ^2.6.0
  mobkit_dashed_border: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - images/
